### ISSUE TITLE
Searchterm in searchbar doesn't copy to advanced search

### ISSUE THREAD

**Issue by OdinJorna** [NicolasPetton/Notebook#12]
In the vanilla TiddlyWIki theme, whenever a user makes a search in the search bar, they can press the 'advanced search' icon to do a deeper search. The search term is then copied into the advanced search tiddler. 

For example, when a user searches for the editor viewtemplate, a normal search isn't sufficient because shadowtiddlers do not show up in the normal search. 

In the Notebook theme, this behaviour is missing. After pressing the advanced search button next to the searchbar, an empty advanced search tiddler shows up. It is a small thing, but it would be a nice QoL improvement to bring this in line with the standard theme.

**Comment by NicolasPetton** [comment]
Thanks for the bug report @OdinJorna. That's someting that was lost was adapting the search bar to work with the upcoming TiddlyWiki 5.1.23. I'll work on a fix.

**Comment by NicolasPetton** [comment]
@OdinJorna I realize now that I fixed it for TiddlyWiki 5.1.23. Making it work for 5.1.22 and 5.1.23 would be hard, because the search feature has changed quite a bit.

Could you try upgrading to 5.1.23 and check if it works for you as well?

**Comment by kookma** [comment]
I can confirm, this issue has gone in TW 5.1.23
