### ISSUE TITLE
Button to empty search bar is missing in 1.2.0

### ISSUE THREAD

**Issue by OdinJorna** [NicolasPetton/Notebook#13]
The x button in the search bar to clear out users search term is missing. See screenshots:

Newest version:
![1](https://user-images.githubusercontent.com/74539616/103296915-6c709780-49f7-11eb-949c-69b24e9dd33a.JPG)

Old version:
![2](https://user-images.githubusercontent.com/74539616/103296927-71354b80-49f7-11eb-923c-fba1b54aee78.JPG)

**Comment by NicolasPetton** [comment]
@OdinJorna thanks for reporting this, I'll investigate.

**Comment by NicolasPetton** [comment]
@OdinJorna The change was actually introduced in TiddlyWiki 5.1.23. I added the clear button back in Notebook.
