### ISSUE TITLE
Suggestion for only hiding default TW side bar while notebook theme is present

### ISSUE THREAD

**Issue by rr-tw5** [NicolasPetton/Notebook#21]
Apologies I don't really know how to use GitHub well.

The notebook theme once installed and opened doesn't allow the sidebar to appear when switching back to vanilla theme (for example).

Why not use the default sidebar code of $:/core/ui/PageTemplate/sidebar
[PageTemplate_sidebar.txt](https://github.com/NicolasPetton/Notebook/files/5819903/PageTemplate_sidebar.txt)

 but just add a reveal on nomatch for your theme?

<$reveal state="$:/theme" type="nomatch" text="$:/themes/nico/notebook">

**Comment by NicolasPetton** [comment]
Hi!

I'm not sure I understand. If I install Notebook but use the Vanilla theme, the defaut sidebar is visible.

Steps to reproduce:

- Go to https://nicolas.petton.fr/tw/notebook.html
- In the ControlPanel, switch the theme to "Vanilla"
- The default sidebar is shown on the right

Am I misunderstanding something?

**Comment by rr-tw5** [comment]
Hi,
So I don't quite understand it, but if you go to: $:/core/ui/PageTemplate/sidebar
And choose to edit it (I was curious in what way you had overwritten it). 
But then cancel (I may have actually ticked (saved)).
Then go to vanilla theme, the sidebar is gone. With the mod I suggested it remains available. 
But I don't understand how what you've written is working. Yet great that it is.

**Comment by rr-tw5** [comment]
Furthermore when I open in edit mode $:/core/ui/PageTemplate/sidebar while in vanilla theme to look at that code, then close it out. When I return to notebook I can't open that tiddler again.

**Comment by NicolasPetton** [comment]
> Then go to vanilla theme, the sidebar is gone. With the mod I suggested it remains available.
But I don't understand how what you've written is working. Yet great that it is.

I think you overwrote the tiddler that was in the notebook theme, that's why the sidebar is gone when you switch back to Vanilla.

> But I don't understand how what you've written is working. Yet great that it is.

The overriding tiddlers in Notebook are only loaded when the theme is active.

**Comment by rr-tw5** [comment]
> The overriding tiddlers in Notebook are only loaded when the theme is active.
OK, so that will also explain why I broke somethings with the shortcuts (I mentioned this in the discussion thread).

I trust you're doing this the best way, please ignore my misunderstandings and suggestions for fixing them.

**Comment by NicolasPetton** [comment]
> I trust you're doing this the best way, please ignore my misunderstandings and suggestions for fixing them.

No problem, thanks for taking the time to report issues here.
