### ISSUE TITLE
Strange Wobbling?

### ISSUE THREAD

**Issue by diego898** [NicolasPetton/Notebook#26]
Hello,

I am experiencing this issue in latest Firefox and safari, on mac. I've hidden your buttons, and I think increased the body font size. 

Now, opening/closing tiddlers causes the entire story river and top bar to "wobble":

![Kapture 2021-01-24 at 17 26 05](https://user-images.githubusercontent.com/742407/105647144-452baf80-5e69-11eb-9062-f4ebf389bd94.gif)

**Comment by NicolasPetton** [comment]
@diego898 thanks for reporting this issue.

Could you upload here an empty wiki that shows the problem? I would make it easier for me to reproduce it.

**Comment by diego898** [comment]
Hey @NicolasPetton I took your notebook.html and added projectify, and tweaked some font settings to reproduce it. I can't upload it here, so here is the file: https://file.io/sDzwW7NHS6or

**Comment by diego898** [comment]
That is what I am experiencing. Strange. So its not a theme issue!
