### ISSUE TITLE
Recent tiddlers button

### ISSUE THREAD

**Issue by diego898** [NicolasPetton/Notebook#27]
Hey Nico, this might not match your preference/aesthetic for Notebook which is fine, but just in case, I think it might be nice to have a "recent tiddlers" dropdown on the top toolbar which shows tiddlers organized by creation date (or maybe modification?). 

I know anyone can make it themselves and add it to the top bar, just placing this here in case you think its useful enough to add to the theme as well.

**Comment by NicolasPetton** [comment]
Hi Diego! Thanks for the suggestion.

I agree that it could be useful in some scenarios, but I think the sidebar section is enough for the general case.
