### ISSUE TITLE
Section title on the left sidebar

### ISSUE THREAD

**Issue by kookma** [NicolasPetton/Notebook#30]
Tiddlers tagged with `$:/tags/SideBar` are displayed on the left sidebar. If they do not have a non-empty caption field, the section appears on the left sidebar with empty title. See below screenshot.

![image](https://user-images.githubusercontent.com/830394/106395165-ef7d7700-6415-11eb-8d0a-744a912ca8b4.png)

You can use the below solution which has a fallback if there is no caption

```
<$view field=caption>
   <$view field=title/>
</$view>
```

**Comment by kookma** [comment]
Furthermore if the caption content is a CamelCase (link) then it is hidden as the link color and section header color are the same.

**Comment by NicolasPetton** [comment]
Thanks for reporting this @kookma.

**Comment by NicolasPetton** [comment]
@kookma I'll go for a slightly different fix using `$transclude` and setting `tv-wikilinks` to `no`, so that transclusion of the caption field still works.
