### ISSUE TITLE
[RFE] compatibility with sticky titles

### ISSUE THREAD

**Issue by Tejeev** [NicolasPetton/Notebook#8]
# Request for Enhancement
## What
Sticky titles are one of the features of the standard UI that I almost can't live without.  I love everything about your theme except that the sticky titles stick over the toolbar layer.  Would be awesome if the title was to stick visibly just below the toolbar or as part of it somehow.

## Examples
Sticky titles: No
![image](https://user-images.githubusercontent.com/8906089/102493977-e144e880-406b-11eb-8e2e-308785a286da.png)
Sticky titles: Yes
![image](https://user-images.githubusercontent.com/8906089/102494040-fb7ec680-406b-11eb-818d-f5eda8ee187c.png)

Requesting something possibly like the following or as some extension of the existing toolbar:
![image](https://user-images.githubusercontent.com/8906089/102494648-e3f40d80-406c-11eb-81ba-fa82bb1840ca.png)

_Also wanted to say thanks a ton for all your work.  I use, love, and recommend this and projectify.. they have really revolutionalized my workflows and made my life more organized :) _

**Comment by NicolasPetton** [comment]
Thanks @Tejeev, I'll push a fix for this soon.

**Comment by Tejeev** [comment]
Thanks Nicolas!
