### ISSUE TITLE
[RFE] Option to hide tags when viewing tiddlers

### ISSUE THREAD

**Issue by Tejeev** [NicolasPetton/Notebook#9]
# Request for Enhancement
## What
I've come to rely on your shields and I don't necessarily need to see aaaallll the many tags I use for organizing and searching and linking things (like projects, etc), just those that are at a glance relevant when reading or working in the wiki.  As such I make shields for the most important ones to highlight them anyway.

This would work well with autogenerating shields https://github.com/NicolasPetton/Shields/issues/1

# Examples
Currently, you see the user-defined tags and those that are used programmatically:
![image](https://user-images.githubusercontent.com/8906089/102498768-4b608c00-4072-11eb-845e-6f01de169cf7.png)

Would be good if it just hid the tags to reveal them on mouseover to create a cleaner UI
![image](https://user-images.githubusercontent.com/8906089/102499207-ce81e200-4072-11eb-8b26-a8b812a8489f.png)
Even if there is a space left for them and the mouseover, it's still cleaner (some tiddlers are starting to build up a lot of tags that I just don't need to have visible...
![image](https://user-images.githubusercontent.com/8906089/102499093-ac885f80-4072-11eb-83ed-f49b3b1a9736.png)

**Comment by NicolasPetton** [comment]
I'm not planning to add that feature to Notebook, but you could add the following tiddler to hide tags, revealing them on mouseover:

```
tags: $:/tags/Stylesheet
title: hidetags.css
type: text/css

.tc-tags-wrapper {
  opacity: 0;
  transition: opacity .15s ease-in;
}
.tc-tags-wrapper:hover {
  opacity: 1;
}
```

**Comment by Tejeev** [comment]
Thank you!  Works like a charm :)
